//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleShopp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public string Address { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
