//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleShopp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int IdProduct { get; set; }
        public int IdClient { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
    }
}
